import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY') || 're_WTfGQ6RB_7Qr6fu83H2FiifJrjq19aP5J';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { email, fullName, phone, company, idCardUrl } = await req.json();

    if (!email) {
      return new Response(JSON.stringify({ error: 'Email is required' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      });
    }

    // 1. Initialize Supabase Admin Client
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // 2. If registration data is provided, create the user explicitly first
    if (fullName) {
      const nameParts = fullName.trim().split(' ');
      const firstName = nameParts[0];
      const lastName = nameParts.slice(1).join(' ');

      const { error: createError } = await supabaseClient.auth.admin.createUser({
        email: email,
        user_metadata: {
          full_name: fullName,
          first_name: firstName,
          last_name: lastName,
          phone: phone,
          company: company,
          id_card_url: idCardUrl
        },
        email_confirm: false
      });
      
      if (createError) {
        if (createError.message.includes('already exists') || createError.message.includes('already registered')) {
          return new Response(JSON.stringify({ error: 'ACCOUNT_EXISTS' }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 400,
          });
        }
        console.error('Error creating new user:', createError);
        return new Response(JSON.stringify({ error: createError.message }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 400,
        });
      }
    }

    // 3. Generate the OTP internally using Supabase Native Auth
    const { data, error } = await supabaseClient.auth.admin.generateLink({
      type: 'magiclink',
      email: email,
    });

    if (error) {
      console.error('Error generating OTP from Supabase:', error);
      return new Response(JSON.stringify({ error: error.message }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      });
    }

    // Extract the raw 6-digit OTP code generated by Supabase
    const otpCode = data.properties?.email_otp;
    
    if (!otpCode) {
      throw new Error('Failed to extract email_otp from Supabase response');
    }

    // 3. Send the OTP email using Resend
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Wearbox <info@onionplease.com>',
        to: email,
        subject: 'Your Wearbox Login Code',
        html: `
          <div style="font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #f8f9fa; padding: 40px 20px; text-align: center;">
            <div style="max-width: 500px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; padding: 40px 30px; box-shadow: 0 4px 20px rgba(0,0,0,0.05);">
              <img src="https://files.catbox.moe/a0glrc.png" alt="Wearbox Logo" width="160" style="margin-bottom: 24px; display: block; margin-left: auto; margin-right: auto;" />
              <h2 style="color: #111111; font-size: 22px; margin-bottom: 12px; font-weight: 700;">Sign in to Wearbox</h2>
              <p style="color: #666666; font-size: 15px; margin-bottom: 32px; line-height: 1.5;">Enter the following secure code in your app to sign in. This code is valid for 10 minutes.</p>
              
              <div style="background-color: #fff0f2; border: 1px solid #ffccd3; border-radius: 8px; padding: 16px; margin-bottom: 32px;">
                <h1 style="color: #E31837; font-size: 42px; font-weight: 800; letter-spacing: 12px; margin: 0; padding-left: 12px;">${otpCode}</h1>
              </div>
              
              <p style="color: #999999; font-size: 13px; margin: 0;">If you didn't request this email, you can safely ignore it.</p>
            </div>
            <div style="margin-top: 24px;">
              <p style="color: #aaaaaa; font-size: 12px;">© 2026 Wearbox Subscription. All rights reserved.</p>
            </div>
          </div>
        `,
      }),
    });

    if (!resendResponse.ok) {
      const resendError = await resendResponse.json();
      console.error('Resend API Error:', resendError);
      throw new Error('Failed to send email via Resend');
    }

    // 4. Return success to the Flutter App
    return new Response(JSON.stringify({ success: true, message: 'OTP sent successfully' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });

  } catch (error) {
    console.error('Edge Function Error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    });
  }
});
